### ISSUE TITLE
helioimage2fits not working in deployment environment

### ISSUE THREAD

**Issue by surajit4444mondal** [ovro-eovsa/ovro-lwa-solar#19]
Bin suggested to just add helioimage2fits in the OVRO-LWA solar pipeline. Surajit will test it out in the deployment environment.

**Comment by binchensun** [comment]
Can we close this issue, as we are no longer using the deployment environment? @surajit4444mondal

**Comment by surajit4444mondal** [comment]
Not relevant anymore. Hence I am closing this issue.
