### ISSUE TITLE
[urgent] calim host setting unknown

### ISSUE THREAD

**Issue by sageyu123** [ovro-eovsa/ovro-lwa-solar#34]
For anyone encountering issues due to the `calim7` hostname not being recognized: this error occurs if `calim7` is not defined in your `.ssh/config`. Ensure the hostname is correctly configured to avoid this problem.

I encountered the following error:
```
Downloading time 2024-01-29T16:33:30.000
No files to download. Abort...
ssh: Could not resolve hostname calim7: Name or service not known
ssh: Could not resolve hostname calim7: Name or service not known
ssh: Could not resolve hostname calim7: Name or service not known
```

Additionally, regarding the `solar_realtime_pipeline.py` script: it's located in the main directory of the [ovro-lwa-solar repository](https://github.com/binchensun/ovro-lwa-solar). For it to be installable via pip, it should be moved to the `ovrolwasolar` subdirectory.

**Comment by binchensun** [comment]
Issue has been resolved.
