### ISSUE TITLE
Apply refraction corrections directly to level 1.5 FITS files

### ISSUE THREAD

**Issue by binchensun** [ovro-eovsa/ovro-lwa-solar#55]
Currently a separate hdu column is added:
https://github.com/ovro-eovsa/ovro-lwa-solar/blob/main/ovrolwasolar/refraction_correction.py#L136

Then the plotting routine takes them and apply:
https://github.com/ovro-eovsa/ovro-lwa-solar/blob/main/ovrolwasolar/visualization.py#L114-L120

For level 1.5 fits files, similar to other instruments such as SDO/AIA, we should instead directly change the CRVAL1 and CRVAL2 values according to the shifts, update the "LVL_NUM" keyword to 1.5, and include a history (processed by a specific version of ovrolwasolar at some date). Thinking twice, I think a separate hdu column may be unnecessary. The FITS keywords of REFRA_PXi should be sufficient to recover the original coordinates. Discussions welcome!

**Comment by peijin94** [comment]
CRVAL1 and CRVAL2 would be different for each freq,
can't do this in the classical SDO way
One possible workaround is adding two columns of CRVALs_1 and CRVALs_2?

**Comment by binchensun** [comment]
Also I think refraction_fit_param() needs to return px, py, as well as a timestamp. The entire array of corrections is unnecessary and is dependent on the exact frequency structure of the FITS file. When applying the refraction corrections to a FITS file, we can take these coefficients, timestamp, and frequency information to calculate new arrays and apply them.

**Comment by binchensun** [comment]
> CRVAL1 and CRVAL2 would be different for each freq, can't do this in the classical SDO way One possible workaround is adding two columns of CRVALs_1 and CRVALs_2?

Good point. In this case, can we shift the images for each frequency plane directly and keep the original CRVALi unchanged? Having nonstandard FITS files may have compatibility issues with other software, such as SunPy, ndcube, etc.

**Comment by dgary50** [comment]
I agree it is better to shift the images.  This facilitates direct plotting of spectra in the assembled data cube after reading.

**Comment by sageyu123** [comment]
Just saw this thread. I agree with the conclusion of shifting the images. We only need to keep the shift vs frequency in X and Y as two table columns in the FITS file.

**Comment by peijin94** [comment]
We come to an agreement that the lev 1.5 is a resampled file with the correction parameters in the header.
